controllers:
    resource: '../src/Controller/'
    type: annotation

catch_all:
    path: /{any}
    controller: 'App\Controller\ErrorController::showException'
    requirements:
        any: '.+'
error_404:
    path: /{any}
    controller: 'App\Controller\ErrorController::showException'
