controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
# Catch-all route for 404 errors
# catch_all:
# path: /{any}# controller: App\Controller\ErrorController::notFound
# requirements:
#     any: .+
logout:
    path: /logout
    controller: App\Controller\SecurityController::logout
# loggedOut:
#     path: /Out
#     controller: App\Controller\UserController::Out
logout_redirect:
    path: /Out
    controller: App\Controller\UserController::Out

